"""Best-of-N + LLM-as-judge chat model wrapper.

Wraps any LangChain-compatible chat model so that every invocation fans out N
parallel candidate generations at elevated temperature, then asks a judge model
to score the candidates. The wrapper returns the highest-scoring candidate
verbatim — synthesis is deliberately out of scope.

Design notes (see `~/.claude/plans/i-think-e-sounds-floofy-moonbeam.md` for the
full spec):

* Diversity is non-negotiable. The wrapper enforces an effective generator
  temperature of `max(generator_temp, 0.7)` unless overridden, since low
  temperatures cause the N candidates to collapse to near-identical outputs.
* The judge sees all N candidates plus the original prompt and returns
  structured JSON: a per-candidate score plus a one-line reasoning summary.
  We then return `candidates[argmax(scores)]`.
* On judge failure, fall back to candidate 0 with a warning. Don't fail
  the call — best-of-N is a quality lever, not a correctness contract.
* `n=1` short-circuits: single generator call, no judge.
* MLflow tracing emits a parent `best_of_n` span with N candidate child spans
  and one judge child span. Span attributes carry the score distribution so
  the technique itself can be measured offline.
"""

from __future__ import annotations

import asyncio
import contextvars
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Optional, Sequence

import mlflow
from langchain_core.callbacks import (
    AsyncCallbackManagerForLLMRun,
    CallbackManagerForLLMRun,
)
from langchain_core.language_models import LanguageModelLike
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.outputs import ChatGeneration, ChatResult
from langchain_core.runnables import Runnable, RunnableConfig
from loguru import logger
from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "BestOfNChatModel",
    "CandidateScore",
    "JudgeDecision",
]


# Floor applied when caller hasn't set `temperature_override` — picked from the
# consensus across Self-Consistency (Wang 2022, T=0.7), Tree-of-Thoughts
# (Yao 2023, T=0.7-1.0), and Let's Verify Step by Step (OpenAI 2023, T=1.0).
_DIVERSITY_TEMPERATURE_FLOOR = 0.7


class CandidateScore(BaseModel):
    """Per-candidate score returned by the judge."""

    index: int = Field(description="Zero-based candidate index, 0..N-1.")
    score: float = Field(description="Quality score, 1.0 (worst) through 10.0 (best).")
    rationale: str = Field(description="Short one-line justification for this score.")


class JudgeDecision(BaseModel):
    """Structured output the judge returns for one best-of-N invocation."""

    scores: list[CandidateScore] = Field(
        description="One score entry per candidate. Length must equal N.",
    )
    reasoning: str = Field(
        description="One-line summary of how candidates were compared.",
    )


def _format_judge_prompt(
    original_messages: Sequence[BaseMessage],
    candidates: Sequence[str],
) -> str:
    """Build the judge prompt: original task + the N labelled candidate responses."""

    original_block_lines: list[str] = []
    for msg in original_messages:
        role = getattr(msg, "type", msg.__class__.__name__).upper()
        content = msg.content if isinstance(msg.content, str) else str(msg.content)
        original_block_lines.append(f"[{role}] {content}")
    original_block = "\n".join(original_block_lines)

    candidate_block_lines: list[str] = []
    for i, text in enumerate(candidates):
        candidate_block_lines.append(f"[Candidate {i}]\n{text}\n")
    candidate_block = "\n".join(candidate_block_lines)

    return (
        "You are an impartial judge selecting the best response to a task.\n\n"
        "Original task (the user-facing request and any system context):\n"
        f"{original_block}\n\n"
        f"You will see {len(candidates)} candidate responses, generated by a single "
        "model at elevated temperature so they are not identical. Your job is to "
        "score each candidate from 1.0 (worst) through 10.0 (best) on how well it "
        "responds to the task. Prioritise correctness, helpfulness, and faithfulness "
        "to the request. Penalise verbosity and hedging.\n\n"
        f"Candidates:\n\n{candidate_block}\n\n"
        "Return one CandidateScore per candidate (length must equal "
        f"{len(candidates)}) plus a one-line reasoning summary. Do NOT pick a "
        "winner explicitly — the calling system uses argmax(scores) and would "
        "rather see your honest score distribution than a forced choice."
    )


class BestOfNChatModel(BaseChatModel):
    """Chat model wrapper implementing best-of-N + LLM-as-judge.

    Acts as a drop-in `BaseChatModel`: callers can use it with
    `bind_tools`, `with_structured_output`, etc. — the binding propagates
    through to each parallel candidate call.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    generator: Any = Field(
        description="The wrapped chat model used to produce candidates. "
        "May be a BaseChatModel or a Runnable (e.g., with_fallbacks).",
    )
    judge_runnable: Any = Field(
        description="A runnable that consumes a string prompt and returns a JudgeDecision. "
        "Built once at construction by calling judge.with_structured_output(JudgeDecision).",
    )
    n: int = Field(description="Number of parallel candidates to generate.")

    @property
    def _llm_type(self) -> str:
        return "best_of_n"

    @classmethod
    def from_components(
        cls,
        generator: LanguageModelLike,
        judge: LanguageModelLike,
        n: int,
        generator_temperature: Optional[float],
        temperature_override: Optional[float],
    ) -> "BestOfNChatModel":
        """Construct a BestOfNChatModel by wiring temperature and judge bindings.

        Applies the diversity-temperature rule:
            effective_temp = temperature_override if set
                             else max(generator_temperature, _DIVERSITY_TEMPERATURE_FLOOR)

        The temperature is bound onto the generator via `.bind(temperature=...)`
        so each parallel call carries the elevated temperature without mutating
        the original InferenceEndpointModel state.
        """

        if temperature_override is not None:
            effective_temp = float(temperature_override)
        else:
            base = generator_temperature if generator_temperature is not None else 0.0
            effective_temp = max(float(base), _DIVERSITY_TEMPERATURE_FLOOR)

        diverse_generator = generator.bind(temperature=effective_temp)
        judge_runnable = judge.with_structured_output(JudgeDecision)

        logger.debug(
            "BestOfNChatModel constructed",
            n=n,
            effective_generator_temperature=effective_temp,
        )

        return cls(
            generator=diverse_generator,
            judge_runnable=judge_runnable,
            n=n,
        )

    def _candidate_text(self, candidate: AIMessage) -> str:
        """Best-effort string extraction for the judge prompt."""
        if isinstance(candidate.content, str):
            return candidate.content
        return str(candidate.content)

    def _generate(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> ChatResult:
        if self.n == 1:
            return self._invoke_generator_sync(messages, stop, kwargs)

        with mlflow.start_span(name="best_of_n", span_type="CHAIN") as parent:
            parent.set_attribute("n", self.n)

            # MLflow span context lives in contextvars and does NOT cross
            # thread boundaries by default. Snapshot the current context per
            # worker thread so each candidate span attaches to this parent.
            with ThreadPoolExecutor(max_workers=self.n) as ex:
                futures = [
                    ex.submit(
                        contextvars.copy_context().run,
                        self._candidate_call_sync,
                        messages,
                        stop,
                        kwargs,
                        i,
                    )
                    for i in range(self.n)
                ]
                candidates: list[AIMessage] = [f.result() for f in futures]

            return self._judge_and_select(messages, candidates, parent)

    async def _agenerate(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> ChatResult:
        if self.n == 1:
            return await self._invoke_generator_async(messages, stop, kwargs)

        with mlflow.start_span(name="best_of_n", span_type="CHAIN") as parent:
            parent.set_attribute("n", self.n)

            tasks = [
                self._candidate_call_async(messages, stop, kwargs, i)
                for i in range(self.n)
            ]
            candidates: list[AIMessage] = await asyncio.gather(*tasks)

            return self._judge_and_select(messages, candidates, parent)

    def _candidate_call_sync(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]],
        kwargs: dict[str, Any],
        index: int,
    ) -> AIMessage:
        with mlflow.start_span(name=f"candidate_{index}", span_type="LLM"):
            invoke_kwargs = dict(kwargs)
            if stop is not None:
                invoke_kwargs["stop"] = stop
            return self.generator.invoke(messages, **invoke_kwargs)

    async def _candidate_call_async(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]],
        kwargs: dict[str, Any],
        index: int,
    ) -> AIMessage:
        with mlflow.start_span(name=f"candidate_{index}", span_type="LLM"):
            invoke_kwargs = dict(kwargs)
            if stop is not None:
                invoke_kwargs["stop"] = stop
            return await self.generator.ainvoke(messages, **invoke_kwargs)

    def _invoke_generator_sync(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]],
        kwargs: dict[str, Any],
    ) -> ChatResult:
        invoke_kwargs = dict(kwargs)
        if stop is not None:
            invoke_kwargs["stop"] = stop
        candidate = self.generator.invoke(messages, **invoke_kwargs)
        return ChatResult(generations=[ChatGeneration(message=candidate)])

    async def _invoke_generator_async(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]],
        kwargs: dict[str, Any],
    ) -> ChatResult:
        invoke_kwargs = dict(kwargs)
        if stop is not None:
            invoke_kwargs["stop"] = stop
        candidate = await self.generator.ainvoke(messages, **invoke_kwargs)
        return ChatResult(generations=[ChatGeneration(message=candidate)])

    def _judge_and_select(
        self,
        original_messages: Sequence[BaseMessage],
        candidates: Sequence[AIMessage],
        parent_span: Any,
    ) -> ChatResult:
        candidate_texts = [self._candidate_text(c) for c in candidates]
        judge_prompt = _format_judge_prompt(original_messages, candidate_texts)

        try:
            with mlflow.start_span(name="judge", span_type="LLM"):
                decision: JudgeDecision = self.judge_runnable.invoke(judge_prompt)
        except Exception as exc:
            logger.warning(
                "best_of_n judge call failed; returning candidate 0: {error_type}: {error}",
                error_type=type(exc).__name__,
                error=str(exc),
            )
            parent_span.set_attribute("judge_failed", True)
            parent_span.set_attribute("judge_error", f"{type(exc).__name__}: {exc}")
            return ChatResult(generations=[ChatGeneration(message=candidates[0])])

        winner_index = self._select_winner_index(decision, len(candidates))
        parent_span.set_attribute("selected_index", winner_index)
        parent_span.set_attribute(
            "scores",
            [s.score for s in decision.scores],
        )
        parent_span.set_attribute("judge_reasoning", decision.reasoning)

        return ChatResult(
            generations=[ChatGeneration(message=candidates[winner_index])]
        )

    @staticmethod
    def _select_winner_index(decision: JudgeDecision, n: int) -> int:
        """Argmax of scores. Defends against malformed judge output."""
        if not decision.scores:
            logger.warning("judge returned empty scores; using candidate 0")
            return 0
        # argmax with deterministic tie-break on lowest index
        best_index = 0
        best_score = float("-inf")
        for entry in decision.scores:
            if 0 <= entry.index < n and entry.score > best_score:
                best_index = entry.index
                best_score = entry.score
        return best_index

    def bind_tools(self, tools: Any, **kwargs: Any) -> "BestOfNChatModel":
        """Forward tool-binding to the inner generator so each candidate carries the tools."""
        new_generator = self.generator.bind_tools(tools, **kwargs)
        return self.__class__(
            generator=new_generator,
            judge_runnable=self.judge_runnable,
            n=self.n,
        )

    def with_structured_output(
        self, schema: Any, **kwargs: Any
    ) -> "_BestOfNStructuredOutput":
        """Run N parallel structured-output calls, then have the judge pick the winner.

        Default `BaseChatModel.with_structured_output` raises NotImplementedError;
        without this override, callers like the dao-ai verifier (which wraps
        `llm.with_structured_output(VerificationResult).invoke(prompt)` in a
        try/except) silently fall back to a default value and best-of-N never
        actually runs. This implementation returns a Runnable that fans out N
        structured-output calls on the inner generator, then asks the judge to
        score the N parsed instances (serialised to JSON for the judge prompt).
        The winning instance is returned verbatim — never synthesised.
        """
        structured_generator = self.generator.with_structured_output(schema, **kwargs)
        return _BestOfNStructuredOutput(
            structured_generator=structured_generator,
            judge_runnable=self.judge_runnable,
            n=self.n,
            schema_name=getattr(schema, "__name__", str(schema)),
        )


def _serialize_candidate_for_judge(candidate: Any) -> str:
    """Serialise a structured-output candidate for inclusion in the judge prompt.

    Pydantic models become indented JSON; dicts go to JSON; everything else
    falls through to str(). Keeps judge prompts comparable across schema types.
    """
    if isinstance(candidate, BaseModel):
        return candidate.model_dump_json(indent=2)
    if isinstance(candidate, dict):
        import json

        return json.dumps(candidate, indent=2, default=str)
    return str(candidate)


class _BestOfNStructuredOutput(Runnable):
    """Runnable returned by `BestOfNChatModel.with_structured_output`.

    Fans out N structured-output invocations on the wrapped generator, then
    judges the N parsed instances and returns the winner. Mirrors the chat
    path's MLflow span shape: parent `best_of_n` + N `candidate_*` + 1 `judge`.
    """

    def __init__(
        self,
        structured_generator: Runnable,
        judge_runnable: Any,
        n: int,
        schema_name: str,
    ) -> None:
        self._gen = structured_generator
        self._judge = judge_runnable
        self._n = n
        self._schema_name = schema_name

    def _candidate_call_sync(self, input_value: Any, index: int) -> Any:
        with mlflow.start_span(name=f"candidate_{index}", span_type="LLM"):
            return self._gen.invoke(input_value)

    async def _candidate_call_async(self, input_value: Any, index: int) -> Any:
        with mlflow.start_span(name=f"candidate_{index}", span_type="LLM"):
            return await self._gen.ainvoke(input_value)

    def _judge_and_select(
        self,
        original_input: Any,
        candidates: Sequence[Any],
        parent_span: Any,
    ) -> Any:
        candidate_texts = [_serialize_candidate_for_judge(c) for c in candidates]
        original_messages: Sequence[BaseMessage]
        if isinstance(original_input, str):
            from langchain_core.messages import HumanMessage

            original_messages = [HumanMessage(content=original_input)]
        elif isinstance(original_input, BaseMessage):
            original_messages = [original_input]
        elif isinstance(original_input, list) and all(
            isinstance(m, BaseMessage) for m in original_input
        ):
            original_messages = original_input
        else:
            from langchain_core.messages import HumanMessage

            original_messages = [HumanMessage(content=str(original_input))]

        judge_prompt = _format_judge_prompt(original_messages, candidate_texts)

        try:
            with mlflow.start_span(name="judge", span_type="LLM"):
                decision: JudgeDecision = self._judge.invoke(judge_prompt)
        except Exception as exc:
            logger.warning(
                "best_of_n structured-output judge call failed; "
                "returning candidate 0: {error_type}: {error}",
                error_type=type(exc).__name__,
                error=str(exc),
            )
            parent_span.set_attribute("judge_failed", True)
            parent_span.set_attribute("judge_error", f"{type(exc).__name__}: {exc}")
            return candidates[0]

        winner_index = BestOfNChatModel._select_winner_index(decision, len(candidates))
        parent_span.set_attribute("selected_index", winner_index)
        parent_span.set_attribute("scores", [s.score for s in decision.scores])
        parent_span.set_attribute("judge_reasoning", decision.reasoning)
        return candidates[winner_index]

    def invoke(
        self, input: Any, config: Optional[RunnableConfig] = None, **kwargs: Any
    ) -> Any:
        if self._n == 1:
            return self._gen.invoke(input)
        with mlflow.start_span(name="best_of_n", span_type="CHAIN") as parent:
            parent.set_attribute("n", self._n)
            parent.set_attribute("schema", self._schema_name)
            with ThreadPoolExecutor(max_workers=self._n) as ex:
                futures = [
                    ex.submit(
                        contextvars.copy_context().run,
                        self._candidate_call_sync,
                        input,
                        i,
                    )
                    for i in range(self._n)
                ]
                candidates = [f.result() for f in futures]
            return self._judge_and_select(input, candidates, parent)

    async def ainvoke(
        self, input: Any, config: Optional[RunnableConfig] = None, **kwargs: Any
    ) -> Any:
        if self._n == 1:
            return await self._gen.ainvoke(input)
        with mlflow.start_span(name="best_of_n", span_type="CHAIN") as parent:
            parent.set_attribute("n", self._n)
            parent.set_attribute("schema", self._schema_name)
            tasks = [self._candidate_call_async(input, i) for i in range(self._n)]
            candidates = await asyncio.gather(*tasks)
            return self._judge_and_select(input, candidates, parent)
